[package]
name = "logrotate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
flate2 = "1.0.28"
log = { version = "0.4.20", features = ["std"] }
